site_name: stacket.in
site_url: https://docs.stacket.in
site_author: you
site_description: This website is a documentation site for Stacket software developers.

nav:
  - "Getting Started":
      - "Introduction": "getting-started/index.md"
      - "Frontend": "getting-started/frontend.md"
      - "Backend": "getting-started/backend.md"
      - "Database": "getting-started/database.md"
  - "About":
      - "Introduction": "index.md"

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml

plugins:
  - search
  - minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
