site_name: stacket.in
site_url: https://docs.stacket.in
site_author: you
site_description: This website is a documentation site for Stacket software developers.

nav:
  - "Getting Started":
      - "Introduction": "getting-started/index.md"
      - "Frontend": "getting-started/frontend.md"
      - "Backend": "getting-started/backend.md"
      - "Database": "getting-started/database.md"
  - "About":
      - "Introduction": "index.md"

theme:
  name: gitbook
  highlightjs: true
  hljs_languages:
    - yaml

plugins: []
